{
 "title": "My App SPA via Prometheus Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "My app SPA requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_requests_total { app=\"myapp-spa\" }"
    }
   ]
  }
 ]
}
{
 "title": "NGINX Ingress controller",
 "description": "Ingress-nginx supports a rich collection of prometheus metrics. If you have prometheus and grafana installed on your cluster then prometheus will already be scraping this data due to the scrape annotation on the deployment.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "singlestat",
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_namespace=~\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{kubernetes_pod_name=~\"$controller\",namespace=~\"$namespace\",ingress=~\"$ingress\"}) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}
{
 "title": "Azure Monitor - Prometheus exports",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "50,75,80,85,90,95,96,97,98,99,99.9"
   },
   {
    "name": "app",
    "label": "App",
    "query": "InsightsMetrics\n| where Namespace == \"prometheus\"\n| distinct tostring(parse_json(Tags).app)"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "InsightsMetrics\n| where Namespace == \"prometheus\"\n| distinct Name"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod metrics via Prometheus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "InsightsMetrics\r\n| where Namespace == \"prometheus\"\r\n| where Name == \"$metric\"\n| extend podName = tostring(parse_json(Tags).pod_name\r)\n| summarize metrics = percentile(Val,$percentile) by bin(TimeGenerated, $__interval), podName\r\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "0d163583-b901-4764-998a-065b52e55799"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.OperationalInsights/workspaces",
      "metricName": "select",
      "metricNamespace": "Microsoft.OperationalInsights/workspaces",
      "resourceGroup": "cloudnative-demo",
      "resourceName": "logs-demo-e25wbosx",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "a0f4a733-4fce-4d49-b8a8-d30541fc1b45"
    }
   ]
  }
 ]
}
{
 "title": "Azure Monitor for Containers - Metrics",
 "description": "Azure Monitor - Container Insights metrics for Kubernetes clusters. Cluster utilization, namespace utilization, Node cpu & memory, Node disk usage & disk io, node network & kubelet docker operation metrics. Many more metrics that are queriable from the log analytics workspace used by Azure monitor for containers!",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterid",
    "label": "Cluster",
    "query": "KubePodInventory | summarize n=count() by ClusterId |project ClusterId "
   },
   {
    "name": "ptile",
    "label": "Percentile (applicable for percentile charts)",
    "query": "50,75,80,85,90,95,96,97,98,99,99.9"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster - Overview & utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "clusterid",
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Utilization",
     "type": "gauge",
     "description": "% Allocatable CPU used across all nodes in the cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rlet allocatable = Perf | where ObjectName == \"K8SNode\" | where CounterName == \"cpuCapacityNanoCores\" \r\n| where $__timeFilter(TimeGenerated) \r\n| where InstanceName startswith '$clusterid'\n| summarize arg_max(TimeGenerated, * ) by Computer\r\n| summarize a=toreal(sum(CounterValue) /1000000)\r\n| project a, b=\"abc\";\r\n\r\nallocatable \r\n| join kind=inner (\r\n    Perf | where ObjectName == \"K8SNode\" | where CounterName == \"cpuUsageNanoCores\" \r\n    | where $__timeFilter(TimeGenerated) \r\n    | where InstanceName startswith '$clusterid'\n    | summarize arg_max(TimeGenerated, * ) by Computer\r\n    | summarize x=toreal(sum(CounterValue) /1000000)\r\n    | project x,y=\"abc\"\r\n) on $left.b == $right.y\r\n|project now(), (x/a) * 100",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Cluster Memory Utilization",
     "type": "gauge",
     "description": "% Allocatable memory (workingset) used across all nodes in the cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\r\nlet allocatable = Perf | where ObjectName == \"K8SNode\" | where CounterName == \"memoryCapacityBytes\" \r\n| where $__timeFilter(TimeGenerated) \r\n| where InstanceName startswith '$clusterid'\n| summarize arg_max(TimeGenerated, * ) by Computer\r\n| summarize a=toreal(sum(CounterValue))\r\n| project a, b=\"abc\";\r\n\r\nallocatable \r\n| join kind=inner (\r\n    Perf | where ObjectName == \"K8SNode\" | where CounterName == \"memoryWorkingSetBytes\" \r\n    | where $__timeFilter(TimeGenerated) \r\n    | where InstanceName startswith '$clusterid'\n    | summarize arg_max(TimeGenerated, * ) by Computer\r\n    | summarize x=toreal(sum(CounterValue))\r\n    | project x,y=\"abc\"\r\n) on $left.b == $right.y\r\n|project now(), (x/a) * 100",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Node count by Status",
     "type": "graph",
     "description": "Number of nodes in the cluster grouped by status",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\r\nKubeNodeInventory\r\n| where ClusterId == '$clusterid'\n| where $__timeFilter(TimeGenerated)\n| summarize count() by bin(TimeGenerated, $__interval), Computer, Status\r\n| summarize arg_max(TimeGenerated, *) by Computer, Status\r\n| summarize nodecount=count() by Status\r\n| project nodecount, Status , now()",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Pod count by status",
     "type": "graph",
     "description": "Pod count grouped by Pod Status",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "KubePodInventory | where ClusterId == '$clusterid'\n| where $__timeFilter(TimeGenerated)\r\n| summarize count() by bin(TimeGenerated, $__interval), PodUid, PodStatus\r\n| summarize arg_max(TimeGenerated, *) by PodUid, PodStatus\r\n| summarize podCount = count() by PodStatus\r\n| project podCount, PodStatus , now() \r\n",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Controller count by Controller Kind",
     "type": "graph",
     "description": "Number of controllers in the cluster by Controller Kind",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\r\nKubePodInventory | where ClusterId == '$clusterid' | where $__timeFilter(TimeGenerated) \n| summarize count() by bin(TimeGenerated, $__interval), PodUid, ControllerKind\r\n| summarize arg_max(TimeGenerated, *) by PodUid, ControllerKind\r\n| summarize controllerCount = count() by ControllerKind\r\n| extend ControllerKind=iif(isempty(ControllerKind), \"None\", ControllerKind)\n| project ControllerKind, controllerCount , now() ",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Node disks with > 80% used space",
     "type": "graph",
     "description": "% Used Disk grouped by Disk in each node where usage > 80%",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\r\nInsightsMetrics\r\n| extend tags=todynamic(Tags) \r\n| where Name ==\"used_percent\"\r\n| where tags[\"container.azm.ms/clusterId\"] == '$clusterid'\n| where $__timeFilter(TimeGenerated) \n| extend hostName=tags.hostName\r\n| extend device=tags.device\r\n| extend disk=strcat(device, \"/\" , hostName) \r\n| summarize arg_max(TimeGenerated, *) by disk\r\n| where Val > 80.0\n| sort by Val desc\n| project Val, disk, now()",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster - Namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "clusterid",
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Namespace count",
     "type": "singlestat",
     "description": "Number of namespaces in the cluster",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "KubePodInventory | where ClusterId == '$clusterid' \r| where $__timeFilter(TimeGenerated)\n| summarize count() by bin(TimeGenerated, $__interval), Namespace\r\n| summarize arg_max(TimeGenerated, *) by Namespace\r\n| summarize namespaceCount = count()\r\n| project namespaceCount,now() ",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Pod count by Kubernetes Namespace",
     "type": "graph",
     "description": "Number of pods per namespace",
     "gridPos": { "h": 8, "w": 6, "x": 3, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rKubePodInventory \n\r| where ClusterId == '$clusterid'\n| where $__timeFilter(TimeGenerated)\n| summarize count() by bin(TimeGenerated, $__interval), PodUid, Namespace\r\n| summarize arg_max(TimeGenerated, *) by PodUid, Namespace\r\n| summarize namespaceCount = count() by Namespace\r\n| sort by namespaceCount desc\n| project namespaceCount, Namespace, now() ",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Controller count by Kubernetes Namespace",
     "type": "graph",
     "description": "Number of controllers per namespace",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rKubePodInventory \n\r| where ClusterId == '$clusterid'\n| where $__timeFilter(TimeGenerated)\n| summarize count() by bin(TimeGenerated, $__interval), PodUid, Namespace\r, ControllerKind\n| summarize arg_max(TimeGenerated, *) by PodUid, Namespace\r, ControllerKind\n| summarize controllerCountByNamespace = count() by Namespace\r, ControllerKind\n| sort by controllerCountByNamespace desc\n| project controllerCountByNamespace, Namespace, now() \n\n",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Controller Kind by Kubernetes Namespace (namespace/controllerkind)",
     "type": "graph",
     "description": "Number of controllers per namespace per kind",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rKubePodInventory \n\r| where ClusterId == '$clusterid'\n| where $__timeFilter(TimeGenerated)\n| summarize count() by bin(TimeGenerated, $__interval), PodUid, Namespace\r, ControllerKind\n| summarize arg_max(TimeGenerated, *) by PodUid, nsc = strcat(Namespace\r,\"/\", ControllerKind)\n| summarize controllerCountByNamespace = count() by nsc\n| sort by controllerCountByNamespace desc\n| project controllerCountByNamespace, nsc, now() \n\n",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Cluster CPU Utilization % by Kubernetes Namespace",
     "type": "graph",
     "description": "CPU % utilized by each namespace",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "let allocatable = Perf | where ObjectName == \"K8SNode\" | where CounterName == \"cpuCapacityNanoCores\" \r\n| where $__timeFilter(TimeGenerated) \r\n| where InstanceName startswith '$clusterid'\n| summarize arg_max(TimeGenerated, * ) by Computer\r\n| summarize a=toreal(sum(CounterValue))\r\n| project a, b=\"abc\";\r\n\r\nallocatable \r\n| join kind=inner (\r\n    Perf | where ObjectName == \"K8SContainer\" | where CounterName == \"cpuUsageNanoCores\" \r\n    | where $__timeFilter(TimeGenerated) \r\n    | where InstanceName startswith '$clusterid'\n    | extend cnameArr = split(InstanceName, \"/\")\r\n    | extend h=array_length(cnameArr)-1\r\n    | extend l=array_length(cnameArr)-2\r\n    | extend cname = strcat(cnameArr[l], \"/\", cnameArr[h])\r\n    | extend x= CounterValue \r\n    | summarize arg_max(TimeGenerated, * ) by cname // | summarize sum(x)\r\n    \r\n    //| summarize x=toreal(sum(CounterValue))\r\n    | project x,y=\"abc\", cname, TimeGenerated\r\n      | join kind=inner ( KubePodInventory\r\n      | where $__timeFilter(TimeGenerated) \r\n      | where ClusterId == '$clusterid'\n      | summarize arg_max(TimeGenerated, *) by ContainerName\r\n      | project ContainerName, Namespace\r\n      ) on $left.cname == $right.ContainerName//)\r\n) on $left.b == $right.y \r\n//| summarize v=arg_max(TimeGenerated,*) by cname,a, Namespace\r\n| summarize xyz= toreal(sum(x)) by a, Namespace\r\n| order by xyz desc\r\n|project now(), (xyz/a) * 100, Namespace \r\n",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Cluster Memory Utilization % by Kubernetes Namespace",
     "type": "graph",
     "description": "Memory usage (working set) by namespace",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "let allocatable = Perf | where ObjectName == \"K8SNode\" | where CounterName == \"memoryCapacityBytes\" \r\n| where $__timeFilter(TimeGenerated) \r\n| where InstanceName startswith '$clusterid'\n| summarize arg_max(TimeGenerated, * ) by Computer\r\n| summarize a=toreal(sum(CounterValue))\r\n| project a, b=\"abc\";\r\n\r\nallocatable \r\n| join kind=inner (\r\n    Perf | where ObjectName == \"K8SContainer\" | where CounterName == \"memoryWorkingSetBytes\" \r\n    | where $__timeFilter(TimeGenerated) \r\n    | where InstanceName startswith '$clusterid'\n    | extend cnameArr = split(InstanceName, \"/\")\r\n    | extend h=array_length(cnameArr)-1\r\n    | extend l=array_length(cnameArr)-2\r\n    | extend cname = strcat(cnameArr[l], \"/\", cnameArr[h])\r\n    | extend x= CounterValue \r\n    | summarize arg_max(TimeGenerated, * ) by cname // | summarize sum(x)\r\n    \r\n    //| summarize x=toreal(sum(CounterValue))\r\n    | project x,y=\"abc\", cname, TimeGenerated\r\n      | join kind=inner ( KubePodInventory\r\n      | where $__timeFilter(TimeGenerated) \r\n      | where ClusterId == '$clusterid'\n      | summarize arg_max(TimeGenerated, *) by ContainerName\r\n      | project ContainerName, Namespace\r\n      ) on $left.cname == $right.ContainerName//)\r\n) on $left.b == $right.y \r\n//| summarize v=arg_max(TimeGenerated,*) by cname,a, Namespace\r\n| summarize xyz= toreal(sum(x)) by a, Namespace\r\n| order by xyz desc\r\n|project now(), (xyz/a) * 100, Namespace  ",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Node - CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "clusterid",
   "collapsed": true,
   "panels": [
    {
     "title": "$ptile-th Percentile % CPU usage by node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "let nodeCpuCapacity=Perf | where CounterName == \"cpuCapacityNanoCores\" | where ObjectName == \"K8SNode\" | where InstanceName startswith '$clusterid' | where $__timeFilter(TimeGenerated)| summarize arg_max(TimeGenerated, *) by Computer| project Computer , cpuCapacity=CounterValue; \n\nlet nodeCpuUsage=Perf | where CounterName == \"cpuUsageNanoCores\"| where ObjectName  == \"K8SNode\"| where InstanceName startswith '$clusterid'| where $__timeFilter(TimeGenerated) | summarize ptileCpuUsage=percentile(CounterValue, $ptile) by Computer, bin(TimeGenerated, $__interval);\n\nnodeCpuUsage|join kind=inner (nodeCpuCapacity) on $left.Computer == $right.Computer| extend ptileCpuUsagepercent=(ptileCpuUsage/cpuCapacity) * 100| order by TimeGenerated asc| project TimeGenerated, Computer, ptileCpuUsagepercent",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "$ptile-th Percentile Memory (rss) usage by node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "let nodeMemoryCapacity=Perf| where CounterName == \"memoryCapacityBytes\"| where ObjectName == \"K8SNode\" | where InstanceName startswith '$clusterid'| where $__timeFilter(TimeGenerated)| summarize arg_max(TimeGenerated, *) by Computer| project Computer , memoryCapacity=CounterValue;\n\nlet nodeMemoryUsage= Perf | where CounterName == \"memoryRssBytes\"| where ObjectName  == \"K8SNode\"| where InstanceName startswith '$clusterid'| where $__timeFilter(TimeGenerated) | summarize ptileMemoryUsage=percentile(CounterValue, $ptile) by Computer, bin(TimeGenerated, $__interval);\n\nnodeMemoryUsage|join kind=inner (nodeMemoryCapacity) on $left.Computer == $right.Computer| extend ptileMemoryUsagepercent=(ptileMemoryUsage/memoryCapacity) * 100| order by TimeGenerated asc| project TimeGenerated, Computer, ptileMemoryUsagepercent",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Node - Disk Usage & IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Used Disk ($ptile-th percentile) by Disk/Node",
     "type": "graph",
     "description": "$ptile-th percentile, % Used Disk grouped by Disk in each node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| extend tags=todynamic(Tags) \r\n| where Name ==\"used_percent\"\r\n| where tags[\"container.azm.ms/clusterId\"] == '$clusterid'\n| where $__timeFilter(TimeGenerated) \n| extend hostName=tags.hostName\r\n| extend device=tags.device\r\n| extend disk=strcat(device, \"/\" , hostName) \r\n| summarize ptileDiskUsagePercentagebyNodeDisk = percentile(Val,$ptile) by bin(TimeGenerated, $__interval), disk\r\n| order by TimeGenerated asc\n| project TimeGenerated, disk, ptileDiskUsagePercentagebyNodeDisk",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "iops in progress ($ptile-th percentile) by Disk/Node",
     "type": "graph",
     "description": "$ptile-th percentile iops in progress grouped by Disk in each node",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| extend tags=todynamic(Tags) \r\n| where Name ==\"iops_in_progress\"\r\n| where tags[\"container.azm.ms/clusterId\"] == '$clusterid'\r\n| where $__timeFilter(TimeGenerated) \n| extend hostName=tags.hostName\r\n| extend device=tags.name\n| extend disk=strcat(device, \"/\" , hostName) \r\n| summarize ptileDiskIopsInProgressbyNodeDisk = percentile(Val,$ptile) by bin(TimeGenerated, $__interval), disk\r\n| order by TimeGenerated asc\n| project TimeGenerated, disk, ptileDiskIopsInProgressbyNodeDisk",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Disk reads/sec ($ptile-th percentile) by disk/node",
     "type": "graph",
     "description": "Reads/sec ($ptile-th percentile) grouped by Disk in each node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/diskio'\r\n| where Name == 'reads'\r\n| where $__timeFilter(TimeGenerated) \n| extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), Device = tostring(Tags.name)\r, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])\n| where clusterId == '$clusterid'\n| extend NodeDisk = strcat(Device, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeDisk, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeDisk asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeDisk) != NodeDisk, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeDisk) != NodeDisk, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeDisk, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Disk write bytes/sec ($ptile-th percentile) by disk/node",
     "type": "graph",
     "description": "Write bytes/sec ($ptile-th percentile) grouped by Disk in each node",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/diskio'\r\n| where Name == 'write_bytes'\r\n| where $__timeFilter(TimeGenerated) \n| extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), Device = tostring(Tags.name)\r, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])\n| where clusterId == '$clusterid'\n| extend NodeDisk = strcat(Device, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeDisk, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeDisk asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeDisk) != NodeDisk, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeDisk) != NodeDisk, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeDisk, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Node - Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "clusterid",
   "collapsed": true,
   "panels": [
    {
     "title": "Network sent bytes/sec ($ptile-th percentile) by interface/node",
     "type": "graph",
     "description": "Sent bytes/sec ($ptile-th percentile) grouped by network interface in each node",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/net'\r\n| where Name == 'bytes_sent'\r\n| where $__timeFilter(TimeGenerated) \n| extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), Interface = tostring(Tags.interface)\r, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])\n| where clusterId == '$clusterid'\n| extend NodeInterface = strcat(Interface, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeInterface, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeInterface asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeInterface) != NodeInterface, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeInterface) != NodeInterface, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeInterface, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Network received bytes/sec ($ptile-th percentile)  by interface/node",
     "type": "graph",
     "description": "Received bytes/sec ($ptile-th percentile) grouped by network interface in each node",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/net'\r\n| where Name == 'bytes_recv'\r\n| where $__timeFilter(TimeGenerated) \n| extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), Interface = tostring(Tags.interface)\r, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])\n| where clusterId == '$clusterid'\n| extend NodeInterface = strcat(Interface, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeInterface, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeInterface asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeInterface) != NodeInterface, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeInterface) != NodeInterface, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeInterface, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Network send errors ($ptile-th percentle) by Interface/Node",
     "type": "graph",
     "description": "Network send errors ($ptile-th percentile) grouped by interface in each node",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| extend tags=todynamic(Tags) \r\n| where Name ==\"err_out\"\r\n| where tags[\"container.azm.ms/clusterId\"] == '$clusterid'\n| where $__timeFilter(TimeGenerated) \n| extend hostName=tags.hostName\n| extend interface=tags.interface\n| extend nodeInterface=strcat(interface, \"/\" , hostName) \r\n| summarize ptileErrorsOutByNodeInterface = percentile(Val,$ptile) by bin(TimeGenerated, $__interval), nodeInterface\n| order by TimeGenerated asc\n| project TimeGenerated, nodeInterface, ptileErrorsOutByNodeInterface",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Network receive errors ($ptile-th percentle) by Interface/Node",
     "type": "graph",
     "description": "Network receive errors ($ptile-th percentile) grouped by interface in each node",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "\rInsightsMetrics\r\n| extend tags=todynamic(Tags) \r\n| where Name ==\"err_in\"\r\n| where tags[\"container.azm.ms/clusterId\"] == '$clusterid'\n| where $__timeFilter(TimeGenerated) \n| extend hostName=tags.hostName\n| extend interface=tags.interface\n| extend nodeInterface=strcat(interface, \"/\" , hostName) \r\n| summarize ptileErrorsInByNodeInterface = percentile(Val,$ptile) by bin(TimeGenerated, $__interval), nodeInterface\n| order by TimeGenerated asc\n| project TimeGenerated, nodeInterface, ptileErrorsInByNodeInterface",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Node - Kubelet Docker Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "clusterid",
   "collapsed": true,
   "panels": [
    {
     "title": "Kubelet Docker Ops/Sec ($ptile-th percentile) by operation/Node",
     "type": "graph",
     "description": "Docker Operations/sec ($ptile-th percentile) grouped by operation in each node",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "InsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/prometheus'\r\n| where Name == 'kubelet_docker_operations'\r\n| where $__timeFilter(TimeGenerated) | extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), optype = tostring(Tags.operation_type)\r\n, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])| where clusterId == '$clusterid'| extend NodeOp = strcat(optype, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeOp, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeOp asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeOp) != NodeOp, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeOp) != NodeOp, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeOp, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Kubelet Docker operation errors/Sec ($ptile-th percentile) by operation/Node",
     "type": "graph",
     "description": "Docker Operation errors/sec ($ptile-th percentile) grouped by operation in each node",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "InsightsMetrics\r\n| where Origin == 'container.azm.ms/telegraf'\r\n| where Namespace == 'container.azm.ms/prometheus'\r\n| where Name == 'kubelet_docker_operations_errors'\r\n| where $__timeFilter(TimeGenerated) | extend Tags = todynamic(Tags)\r\n| extend HostName = tostring(Tags.hostName), optype = tostring(Tags.operation_type)\r\n, clusterId = tostring(Tags[\"container.azm.ms/clusterId\"])| where clusterId == '$clusterid'| extend NodeOp = strcat(optype, \"/\", HostName)\r\n| summarize Val=percentile(Val,$ptile) by NodeOp, TimeGenerated=bin(TimeGenerated,$__interval)\r\n| order by NodeOp asc, TimeGenerated asc\r\n| serialize\r\n| extend PrevVal = iif(prev(NodeOp) != NodeOp, 0.0, prev(Val)), PrevTimeGenerated = iif(prev(NodeOp) != NodeOp, datetime(null), prev(TimeGenerated))\r\n| where isnotnull(PrevTimeGenerated) and PrevTimeGenerated != TimeGenerated\r\n| extend Rate = iif(PrevVal > Val, Val / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1), iif(PrevVal == Val, 0.0, (Val - PrevVal) / (datetime_diff('Second', TimeGenerated, PrevTimeGenerated) * 1)))\r\n| where isnotnull(Rate)\r\n| project TimeGenerated, NodeOp, Rate\r\n|render timechart",
        "resultFormat": "time_series",
        "workspace": ""
       },
       "azureMonitor": {
        "dimensionFilter": "*",
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Dapr System Services Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Health & Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{app=~\"dapr-sentry|dapr-placement|dapr-sidecar-injector|dapr-operator\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total CPU usage (kernel and user)",
   "type": "graph",
   "description": "This shows total amount of kernel and user CPU usage time.",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator).*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage in bytes",
   "type": "graph",
   "description": "The amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{app=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator)\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Number of GO routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_goroutines{app=~\"(dapr-sentry|dapr-sidecar-injector|dapr-placement|dapr-operator)\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "# Services Created",
   "type": "graph",
   "description": "The total number of services created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(dapr_operator_service_created_total) by (app_id)",
     "legendFormat": "{{app_id}}"
    }
   ]
  },
  {
   "title": "# Services Deleted",
   "type": "graph",
   "description": "The total number of services deleted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_operator_service_deleted_total",
     "legendFormat": "{{app_id}}"
    }
   ]
  },
  { "title": "Sidecar Injector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "# sidecar injection requests",
   "type": "graph",
   "description": "The total number of sidecar injection requests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_injector_sidecar_injection_requests_total",
     "legendFormat": "sidecars requests"
    }
   ]
  },
  {
   "title": "# successful sidecar injected",
   "type": "graph",
   "description": "The total number of successful sidecar injection requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_injector_sidecar_injection_succeeded_total",
     "legendFormat": "{{app_id}}"
    }
   ]
  },
  { "title": "CA Sentry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Root/Issuer cert expiry",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(dapr_sentry_issuercert_expiry_timestamp) - time()"
    }
   ]
  },
  {
   "title": "Certificate Signing Requests (CSR) from Daprd",
   "type": "graph",
   "description": "Certificate Signing Request ( CSR ) from Dapr runtime",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_cert_sign_request_received_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Requests"
    },
    {
     "expr": "sum(dapr_sentry_cert_sign_success_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Success"
    },
    {
     "expr": "sum(dapr_sentry_cert_sign_failure_total{app=\"dapr-sentry\"})",
     "legendFormat": "CSR Failure"
    }
   ]
  },
  {
   "title": "CSR Failures",
   "type": "graph",
   "description": "This chart shows the failure reason of Certificate Sign Request.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_cert_sign_failure_total{app=\"dapr-sentry\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Issuer cert and key changed total",
   "type": "graph",
   "description": "This will be counted when issuer cert and key are changed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_issuercert_changed_total{app=\"dapr-sentry\"})"
    }
   ]
  },
  {
   "title": "Server TLS certificate issuance failures",
   "type": "graph",
   "description": "This chart shows the reason of gRPC server TLS certificate issuance failures.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dapr_sentry_servercert_issue_failed_total{app=\"dapr-sentry\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Placement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "# total replicas",
   "type": "graph",
   "description": "The total number of replicas connected to placement service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dapr_placement_hosts_total", "legendFormat": "hosts" }
   ]
  },
  {
   "title": "# replicas not hosting actors",
   "type": "graph",
   "description": "The total number of replicas which are not hosting actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_placement_nonactorhosts_total",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "# actor types",
   "type": "graph",
   "description": "The total number of actor types registered with Dapr runtime.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dapr_placement_actortypes_total",
     "legendFormat": "actor types"
    }
   ]
  }
 ]
}
{
 "title": "Dapr Sidecar Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "NAMESPACE",
    "query": "label_values(dapr_runtime_component_loaded,kubernetes_namespace)"
   },
   {
    "name": "dapr_app_id",
    "label": "APPID",
    "query": "label_values(dapr_runtime_component_loaded,app_id)"
   }
  ]
 },
 "panels": [
  { "title": "Health monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sidecar uptime",
   "type": "stat",
   "description": "This shows the uptime of dapr runtime sidecar. If the sidecar is running for less than 10 minutes, the color will turn into RED.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total CPU usage (Kernel and User)",
   "type": "graph",
   "description": "This shows total amount of Kernel and user CPU usage for Daprd.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"($dapr_app_id).*\", namespace=\"$namespace\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Number of GO routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{kubernetes_name=~\"($dapr_app_id)-dapr.*\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Memory usage in bytes",
   "type": "graph",
   "description": "The amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Managed virtual memory in bytes",
   "type": "graph",
   "description": "The amount of address space that a process is managing. This includes all types of memory, both in RAM and swapped out.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Throughput/Latency - HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound request latency (App->Dapr) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the turn-around latency when user app calls Dapr API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_server_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{method}} {{path}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_server_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{method}} {{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Outbound request rate (App -> Dapr) (RPS)",
     "type": "graph",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_server_response_count{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{method}} {{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request latency (Dapr -> App) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{method}} /{{path}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{method}} /{{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request rate (Dapr -> App) (RPS)",
     "type": "graph",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app HTTP endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_client_completed_count{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{method}} {{path}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput/Latency - gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound request latency (App->Dapr) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the turn-around latency when user app calls Dapr API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_grpc_io_server_server_latency_bucket{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_server_method))",
       "legendFormat": "[95p] - {{grpc_server_method}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_grpc_io_server_server_latency_bucket{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_server_method))",
       "legendFormat": "[75p] {{grpc_server_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Outbound request rate (App -> Dapr) (RPS)",
     "type": "graph",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, grpc_server_method, grpc_server_status) (rate(dapr_grpc_io_server_completed_rpcs{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\"}[5m]))",
       "legendFormat": "{{grpc_server_status}} {{grpc_server_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request latency (Dapr -> App) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_client_method))",
       "legendFormat": "[95p] {{grpc_client_method}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_client_method))",
       "legendFormat": "[75p] {{grpc_client_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request rate (Dapr -> App) (RPS)",
     "type": "graph",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app gRPC endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, grpc_client_method, grpc_client_status) (rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{grpc_client_status}} {{grpc_client_method}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loaded component configurations",
     "type": "stat",
     "description": "This shows the number of configured components. For example, it will shows \"2\" if you configure redis statestore and redis pubsub components. ",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_loaded{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id)",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Initialized components",
     "type": "stat",
     "description": "This shows the number of initialized components. This number must be the same as loaded components. Otherwise, Daprd fails to initialize some of components.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_init_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id)",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Component failures",
     "type": "graph",
     "description": "This chart shows the number component initialization failures with the reasons.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{app_id}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actor Activation",
     "type": "graph",
     "description": "This chart shows how many actors are activated.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dapr_runtime_actor_activated_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "OK {{actor_type}}"
      },
      {
       "expr": "dapr_runtime_actor_activated_failed_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "Error {{actor_type}}"
      }
     ]
    },
    {
     "title": "Actor Deactivation",
     "type": "graph",
     "description": "This chart shows how many actors are deactivated.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dapr_runtime_actor_deactivated_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "OK {{actor_type}}"
      },
      {
       "expr": "dapr_runtime_actor_deactivated_failed_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "Error {{actor_type}}"
      }
     ]
    },
    {
     "title": "Actor table rebalancing",
     "type": "graph",
     "description": "This shows when actor is rebalanced. This operation can make the activated actors deactivated and move actor to the other hosts.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dapr_runtime_actor_rebalanced_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Status report status",
     "type": "graph",
     "description": "This shows when Daprd reports host status to placement service. Non-Actor service reports host status in the beginning. Actor service reports host status to placement periodically. If there is a failure, virtual actors will not be distributed properly.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_actor_status_report_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK ({{app_id}})"
      },
      {
       "expr": "rate(dapr_runtime_actor_status_report_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error ({{app_id}})"
      }
     ]
    },
    {
     "title": "Report status error reasons",
     "type": "bargauge",
     "description": "This shows the failures when Daprd reports host status to placement.",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 17 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_actor_status_report_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, operation)",
       "legendFormat": "{{operation}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Placement table operation",
     "type": "graph",
     "description": "This shows the placement table update status based on the response from placement service. Daprd maintains the actor placement table in its memory. This table is periodically updated.",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dapr_runtime_actor_table_operation_recv_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, operation)",
       "legendFormat": "{{operation}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "mTLS initialization status",
     "type": "graph",
     "description": "This chart  shows when mTLS is initialized, which means root cert is loaded and workload cert is issued from sentry, when runtime starts.",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_mtls_init_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK {{app_id}}"
      },
      {
       "expr": "rate(dapr_runtime_mtls_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error {{app_id}}"
      }
     ]
    },
    {
     "title": "mTLS Initialization Errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 11 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_mtls_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{reason}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Workload certificate rotation status",
     "type": "graph",
     "description": "This chart shows when workload certificate is rotated.",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_mtls_workload_cert_rotated_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK {{app_id}}"
      },
      {
       "expr": "rate(dapr_runtime_mtls_workload_cert_rotated_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error {{app_id}}"
      }
     ]
    },
    {
     "title": "Cert rotation error reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_mtls_workload_cert_rotated_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{reason}} ({{app_id}})"
      }
     ]
    }
   ]
  }
 ]
}