apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: myhpa-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30